package space.bbkr.chase.dsl;

enum TokenType {
	//punctuations
	LEFT_BRACKET, RIGHT_BRACKET, LEFT_PAREN, RIGHT_PAREN, COMMA, DOT, PLUS, MINUS, SLASH, STAR, SEMICOLON, EQUAL, LF,

	//comparisons
	BANG_EQUAL, EQUAL_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,

	//literals
	KEY, IDENTIFIER, INT, FLOAT, STRING, TOML,

	//keywords
	AND, NOT, OR, TRUE, FALSE, IF, ELSE, FROM, WITH, ABSTRACT, REQUIRED, OPTIONAL, NULL, RETURN, PARENT, WHILE, BREAK, FOR,

	//end of file
	/*LEMMA*/EOF
}
